name: iOS build
 
on:
 push:
   branches:
     - development
 
jobs:
 deploy:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
 
     - name: Set up ruby env
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 2.7.2
         bundler-cache: true
 

    
     - name: Build & upload iOS binary
       run: bundle exec fastlane ios build_upload_testflight
