name: Staging

on:
  push:
    branches: [ "release/*" ]
  pull_request:
    branches: [ "release/*" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: fastlane staging
